export const type = {
    SWITCH_ACTIVE_PAGE: "SWITCH_ACTIVE_PAGE",
    SET_GOOD_DATA: "SET_GOOD_DATA",
    FETCH_RATE_DATA: "FETCH_RATE_DATA",
    SET_RATE: "SET_RATE",
    SET_LIST: "SET_LIST",
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
    UPDATE_CURRENCY_IN_CART: "UPDATE_CURRENCY_IN_CART",
    UPDATE_CURRENCY: "UPDATE_CURRENCY",
    ADD_GOOD_TO_CART: "ADD_GOOD_TO_CART",
    FETCH_ACCOUNT_DATA: "FETCH_ACCOUNT_DATA",
    GET_LIST_DATA: "GET_LIST_DATA"
}